### ISSUE TITLE
Enhancement: Add basic udev rule to README.md

### ISSUE THREAD

**Issue by lukost** [embuc/k480_conf#1]
Looking through various forums I found that many people use the software, but complain about the necessity to run the command after every switch/reconnect. Why not add a simple rule for use in udev into the readme so that everybody can find everything in one place?

Here is one of possible rules to be put in `/etc/udev/rules.d/99-k480.rules`:
`SUBSYSTEM=="hidraw", ACTION=="add", SUBSYSTEMS=="bluetooth", ATTRS{address}=="00:1f:20:e3:6c:b6", RUN+="/opt/bin/k480_conf -d /dev/%k -f on"`

**Comment by embuc** [comment]
Thanks for your suggestion I'll add it to the Readme. I tried different variants for this but never get to settle on any - so I'll just add yours :)
