### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by thangngoc89** [embuc/k480_conf#6]
Hey. I just want to say thank for making this great script. I works pretty well for my setup: K480, Ubuntu 18.04 and built-in bluetooth of my laptop (DELL Vostro V5460)

**Comment by embuc** [comment]
You are welcome! Happy that it could help.

**Comment by esturniolo** [comment]
I came here for the same as the initial topic.
You're my hero.

**Comment by gondimjoaom** [comment]
Thank you so much!
